### ISSUE TITLE
Support for async API

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [jcreekmore/timeout-readwrite-rs#17]
Is there any plan for providing a async API for this crate?

I have been working on a async version of similar API to the one provided here in order to make it compatible with other projects that I worked on that are fully async/await. If you are interested I could send a PR adding async versions of timeout reads and writes based on tokio.

**Comment by jcreekmore** [comment]
I am open to looking at it, but I am unsure what the purpose in providing something like that would be when https://docs.rs/tokio/1.15.0/tokio/time/fn.timeout.html exists already for tokio and is basically what I was trying to emulate with this wrapper to begin with.

**Comment by Jonathas-Conceicao** [comment]
The reason I didn't use `tokio::time::timeout` is because I need the timeout to be considered for every poll, and not for the hole future itself. The reader that I use is wrapped into a buffered reader for better code quality, but I need the operation to fail if the disk takes too long to give back any data. And it's my understanding that this crate offers that behavior but for sync read/write.

However, after digging a bit more into this I've found https://github.com/sfackler/tokio-io-timeout, which seems to implement the behavior that I need over AsyncRead/AsyncWrite, so I will be closing this issue.
