### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by otavio** [jcreekmore/timeout-readwrite-rs#9]
Is it possible to get a new release of last changes? I need this to use on my project and it'd be of great help.

**Comment by jcreekmore** [comment]
Sure thing. Honestly, I was waiting a bit to see if you were going to push any more PRs my way before I did the release.

**Comment by jcreekmore** [comment]
Released 0.2.0

**Comment by otavio** [comment]
Just in case you are curious: https://github.com/otavio/updatehub/pull/33
